Check for file

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -38,16 +38,30 @@ jobs:
           pip install opencv-python
           pip install -U Flask
 
+      - name: Install SCons
+        run: sudo apt-get install scons
+
       - name: Build
         run: |
           scons
+
+      - name: Set up GCC
+        uses: Dup4/actions-setup-gcc@v1
+
+      - name: Install binutils
+        run: sudo apt-get install binutils
+
+      - name: Check if all necessary files are present
+        run: |
+          ls ./
+          if [ ! -f flatpak.json ]; then echo "Manifest file not found!"; exit 1; fi
 
   flatpak:
     name: "Flatpak"
     runs-on: ubuntu-latest
     needs: build
     steps:
-    
+
       - name: Set up Flatpak environment
         run: |
           sudo apt-get update -qy
@@ -60,3 +74,10 @@ jobs:
 
       - name: Flatpak Builder
         uses: flatpak/flatpak-github-actions@v6.3
+
+      - name: Upload Flatpak package to GitHub Releases
+        uses: actions/upload-artifact@v2
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          name: flatpak-package
+          path: path/to/your/flatpak-packag
